document.write('<div id="headerAndButtons">')
document.write('	<div id="uheaderAndButtons" class="center">')
document.write('		<div id="strip">')
document.write('			<table id="buttonRow" cellspacing="0" cellpadding="0">')
document.write('				<tr>')
document.write('					<td onMouseOver="buttonChange(1)" onMouseOut="changeBack(1)" onclick="loadHome()" id="button1" align="center"><div id="ubutton1">!!!Home</div></td> ')
document.write('					<td onMouseOver="buttonChange(2)" onMouseOut="changeBack(2)" onclick="loadEstimates()" id="button2" align="center"><div id="ubutton2">!!!Rates</div></td> ')
document.write('					<td onMouseOver="buttonChange(3)" onMouseOut="changeBack(3)" onclick="loadInitiatives()" id="button3" align="center"><div id="ubutton3">!!!Initiatives</div></td> ')
document.write('					<td onMouseOver="buttonChange(4)" onMouseOut="changeBack(4)" onclick="loadContactUs()" id="button4" align="center"><div id="ubutton4">!!!Contact-Us</div></td> ')
document.write('				</tr>')
document.write('			</table>')
document.write('		</div>')
document.write('		<div id="logoBack">')
document.write('			<img id="logo" src="tree.png" onclick="loadHome()" title="Revived"></img>')
document.write('		</div>')
document.write('		<div id="revivedTextBack">')
document.write('			<img id="revivedText" src="textF.png" onclick="loadHome()" title="Revived"></img>')
document.write('		</div>')
document.write('	</div>')
document.write('</div>')